services:
    slingsky-web:
        image: slingsky-web:latest
        container_name: slingsky-web
        hostname: slingsky-web
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "5006:80"
        volumes:
          - ./public:/app/public
          - ./functions/views:/app/functions/views
          - ./functions/index.js:/app/functions/index.js
          - ./functions/firebase.js:/app/functions/firebase.js
          - ./functions/oauth.js:/app/functions/oauth.js
          - ./server.js:/app/server.js
          
    slingsky-tunnel:
        image: cloudflare/cloudflared:latest
        container_name: slingsky-tunnel
        hostname: slingsky-tunnel
        command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
        environment:
          - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
          - TUNNEL_HOSTNAME=dev.slingsky.app
          - TUNNEL_PORT=5006
        depends_on:
          - slingsky-web

